window.esdocSearchIndex = [
  [
    "@data-structure/pairs/src/basepairs.js~basepairs",
    "class/src/BasePairs.js~BasePairs.html",
    "<span>BasePairs</span> <span class=\"search-result-import-path\">@data-structure/pairs/src/BasePairs.js</span>",
    "class"
  ],
  [
    "@data-structure/pairs/src/efficientlyinvertiblepairs.js~efficientlyinvertiblepairs",
    "class/src/EfficientlyInvertiblePairs.js~EfficientlyInvertiblePairs.html",
    "<span>EfficientlyInvertiblePairs</span> <span class=\"search-result-import-path\">@data-structure/pairs/src/EfficientlyInvertiblePairs.js</span>",
    "class"
  ],
  [
    "@data-structure/pairs/src/memoryefficientpairs.js~memoryefficientpairs",
    "class/src/MemoryEfficientPairs.js~MemoryEfficientPairs.html",
    "<span>MemoryEfficientPairs</span> <span class=\"search-result-import-path\">@data-structure/pairs/src/MemoryEfficientPairs.js</span>",
    "class"
  ],
  [
    "@data-structure/pairs/src/insert.js~insert",
    "function/index.html#static-function-insert",
    "<span>insert</span> <span class=\"search-result-import-path\">@data-structure/pairs/src/insert.js</span>",
    "function"
  ],
  [
    "@data-structure/pairs/src/invertiterable.js~invertiterable",
    "function/index.html#static-function-invertIterable",
    "<span>invertIterable</span> <span class=\"search-result-import-path\">@data-structure/pairs/src/invertIterable.js</span>",
    "function"
  ],
  [
    "@data-structure/pairs/src/iterablefrommap.js~iterablefrommap",
    "function/index.html#static-function-iterableFromMap",
    "<span>iterableFromMap</span> <span class=\"search-result-import-path\">@data-structure/pairs/src/iterableFromMap.js</span>",
    "function"
  ],
  [
    "@data-structure/pairs/src/remove.js~remove",
    "function/index.html#static-function-remove",
    "<span>remove</span> <span class=\"search-result-import-path\">@data-structure/pairs/src/remove.js</span>",
    "function"
  ],
  [
    "@data-structure/pairs/src/swap.js~swap",
    "function/index.html#static-function-swap",
    "<span>swap</span> <span class=\"search-result-import-path\">@data-structure/pairs/src/swap.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/basepairs.js",
    "file/src/BasePairs.js.html",
    "src/BasePairs.js",
    "file"
  ],
  [
    "src/basepairs.js~basepairs#[symbol.iterator]",
    "class/src/BasePairs.js~BasePairs.html#instance-method-[Symbol.iterator]",
    "src/BasePairs.js~BasePairs#[Symbol.iterator]",
    "method"
  ],
  [
    "src/basepairs.js~basepairs#add",
    "class/src/BasePairs.js~BasePairs.html#instance-method-add",
    "src/BasePairs.js~BasePairs#add",
    "method"
  ],
  [
    "src/basepairs.js~basepairs#clear",
    "class/src/BasePairs.js~BasePairs.html#instance-method-clear",
    "src/BasePairs.js~BasePairs#clear",
    "method"
  ],
  [
    "src/basepairs.js~basepairs#delete",
    "class/src/BasePairs.js~BasePairs.html#instance-method-delete",
    "src/BasePairs.js~BasePairs#delete",
    "method"
  ],
  [
    "src/basepairs.js~basepairs#entries",
    "class/src/BasePairs.js~BasePairs.html#instance-method-entries",
    "src/BasePairs.js~BasePairs#entries",
    "method"
  ],
  [
    "src/basepairs.js~basepairs#foreach",
    "class/src/BasePairs.js~BasePairs.html#instance-method-forEach",
    "src/BasePairs.js~BasePairs#forEach",
    "method"
  ],
  [
    "src/basepairs.js~basepairs#has",
    "class/src/BasePairs.js~BasePairs.html#instance-method-has",
    "src/BasePairs.js~BasePairs#has",
    "method"
  ],
  [
    "src/basepairs.js~basepairs#keys",
    "class/src/BasePairs.js~BasePairs.html#instance-method-keys",
    "src/BasePairs.js~BasePairs#keys",
    "method"
  ],
  [
    "src/basepairs.js~basepairs#left",
    "class/src/BasePairs.js~BasePairs.html#instance-method-left",
    "src/BasePairs.js~BasePairs#left",
    "method"
  ],
  [
    "src/basepairs.js~basepairs#leftof",
    "class/src/BasePairs.js~BasePairs.html#instance-method-leftOf",
    "src/BasePairs.js~BasePairs#leftOf",
    "method"
  ],
  [
    "src/basepairs.js~basepairs#right",
    "class/src/BasePairs.js~BasePairs.html#instance-method-right",
    "src/BasePairs.js~BasePairs#right",
    "method"
  ],
  [
    "src/basepairs.js~basepairs#rightof",
    "class/src/BasePairs.js~BasePairs.html#instance-method-rightOf",
    "src/BasePairs.js~BasePairs#rightOf",
    "method"
  ],
  [
    "src/basepairs.js~basepairs#update",
    "class/src/BasePairs.js~BasePairs.html#instance-method-update",
    "src/BasePairs.js~BasePairs#update",
    "method"
  ],
  [
    "src/basepairs.js~basepairs#values",
    "class/src/BasePairs.js~BasePairs.html#instance-method-values",
    "src/BasePairs.js~BasePairs#values",
    "method"
  ],
  [
    "src/efficientlyinvertiblepairs.js",
    "file/src/EfficientlyInvertiblePairs.js.html",
    "src/EfficientlyInvertiblePairs.js",
    "file"
  ],
  [
    "src/efficientlyinvertiblepairs.js~efficientlyinvertiblepairs#_imap",
    "class/src/EfficientlyInvertiblePairs.js~EfficientlyInvertiblePairs.html#instance-member-_imap",
    "src/EfficientlyInvertiblePairs.js~EfficientlyInvertiblePairs#_imap",
    "member"
  ],
  [
    "src/efficientlyinvertiblepairs.js~efficientlyinvertiblepairs#_map",
    "class/src/EfficientlyInvertiblePairs.js~EfficientlyInvertiblePairs.html#instance-member-_map",
    "src/EfficientlyInvertiblePairs.js~EfficientlyInvertiblePairs#_map",
    "member"
  ],
  [
    "src/efficientlyinvertiblepairs.js~efficientlyinvertiblepairs#add",
    "class/src/EfficientlyInvertiblePairs.js~EfficientlyInvertiblePairs.html#instance-method-add",
    "src/EfficientlyInvertiblePairs.js~EfficientlyInvertiblePairs#add",
    "method"
  ],
  [
    "src/efficientlyinvertiblepairs.js~efficientlyinvertiblepairs#clear",
    "class/src/EfficientlyInvertiblePairs.js~EfficientlyInvertiblePairs.html#instance-method-clear",
    "src/EfficientlyInvertiblePairs.js~EfficientlyInvertiblePairs#clear",
    "method"
  ],
  [
    "src/efficientlyinvertiblepairs.js~efficientlyinvertiblepairs#constructor",
    "class/src/EfficientlyInvertiblePairs.js~EfficientlyInvertiblePairs.html#instance-constructor-constructor",
    "src/EfficientlyInvertiblePairs.js~EfficientlyInvertiblePairs#constructor",
    "method"
  ],
  [
    "src/efficientlyinvertiblepairs.js~efficientlyinvertiblepairs#delete",
    "class/src/EfficientlyInvertiblePairs.js~EfficientlyInvertiblePairs.html#instance-method-delete",
    "src/EfficientlyInvertiblePairs.js~EfficientlyInvertiblePairs#delete",
    "method"
  ],
  [
    "src/efficientlyinvertiblepairs.js~efficientlyinvertiblepairs#invert",
    "class/src/EfficientlyInvertiblePairs.js~EfficientlyInvertiblePairs.html#instance-method-invert",
    "src/EfficientlyInvertiblePairs.js~EfficientlyInvertiblePairs#invert",
    "method"
  ],
  [
    "src/efficientlyinvertiblepairs.js~efficientlyinvertiblepairs#leftof",
    "class/src/EfficientlyInvertiblePairs.js~EfficientlyInvertiblePairs.html#instance-method-leftOf",
    "src/EfficientlyInvertiblePairs.js~EfficientlyInvertiblePairs#leftOf",
    "method"
  ],
  [
    "src/efficientlyinvertiblepairs.js~efficientlyinvertiblepairs#right",
    "class/src/EfficientlyInvertiblePairs.js~EfficientlyInvertiblePairs.html#instance-method-right",
    "src/EfficientlyInvertiblePairs.js~EfficientlyInvertiblePairs#right",
    "method"
  ],
  [
    "src/efficientlyinvertiblepairs.js~efficientlyinvertiblepairs#size",
    "class/src/EfficientlyInvertiblePairs.js~EfficientlyInvertiblePairs.html#instance-member-size",
    "src/EfficientlyInvertiblePairs.js~EfficientlyInvertiblePairs#size",
    "member"
  ],
  [
    "src/efficientlyinvertiblepairs.js~efficientlyinvertiblepairs.from",
    "class/src/EfficientlyInvertiblePairs.js~EfficientlyInvertiblePairs.html#static-method-from",
    "src/EfficientlyInvertiblePairs.js~EfficientlyInvertiblePairs.from",
    "method"
  ],
  [
    "src/memoryefficientpairs.js",
    "file/src/MemoryEfficientPairs.js.html",
    "src/MemoryEfficientPairs.js",
    "file"
  ],
  [
    "src/memoryefficientpairs.js~memoryefficientpairs#_map",
    "class/src/MemoryEfficientPairs.js~MemoryEfficientPairs.html#instance-member-_map",
    "src/MemoryEfficientPairs.js~MemoryEfficientPairs#_map",
    "member"
  ],
  [
    "src/memoryefficientpairs.js~memoryefficientpairs#add",
    "class/src/MemoryEfficientPairs.js~MemoryEfficientPairs.html#instance-method-add",
    "src/MemoryEfficientPairs.js~MemoryEfficientPairs#add",
    "method"
  ],
  [
    "src/memoryefficientpairs.js~memoryefficientpairs#clear",
    "class/src/MemoryEfficientPairs.js~MemoryEfficientPairs.html#instance-method-clear",
    "src/MemoryEfficientPairs.js~MemoryEfficientPairs#clear",
    "method"
  ],
  [
    "src/memoryefficientpairs.js~memoryefficientpairs#constructor",
    "class/src/MemoryEfficientPairs.js~MemoryEfficientPairs.html#instance-constructor-constructor",
    "src/MemoryEfficientPairs.js~MemoryEfficientPairs#constructor",
    "method"
  ],
  [
    "src/memoryefficientpairs.js~memoryefficientpairs#delete",
    "class/src/MemoryEfficientPairs.js~MemoryEfficientPairs.html#instance-method-delete",
    "src/MemoryEfficientPairs.js~MemoryEfficientPairs#delete",
    "method"
  ],
  [
    "src/memoryefficientpairs.js~memoryefficientpairs#invert",
    "class/src/MemoryEfficientPairs.js~MemoryEfficientPairs.html#instance-method-invert",
    "src/MemoryEfficientPairs.js~MemoryEfficientPairs#invert",
    "method"
  ],
  [
    "src/memoryefficientpairs.js~memoryefficientpairs#size",
    "class/src/MemoryEfficientPairs.js~MemoryEfficientPairs.html#instance-member-size",
    "src/MemoryEfficientPairs.js~MemoryEfficientPairs#size",
    "member"
  ],
  [
    "src/memoryefficientpairs.js~memoryefficientpairs.from",
    "class/src/MemoryEfficientPairs.js~MemoryEfficientPairs.html#static-method-from",
    "src/MemoryEfficientPairs.js~MemoryEfficientPairs.from",
    "method"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/insert.js",
    "file/src/insert.js.html",
    "src/insert.js",
    "file"
  ],
  [
    "src/invertiterable.js",
    "file/src/invertIterable.js.html",
    "src/invertIterable.js",
    "file"
  ],
  [
    "src/iterablefrommap.js",
    "file/src/iterableFromMap.js.html",
    "src/iterableFromMap.js",
    "file"
  ],
  [
    "src/remove.js",
    "file/src/remove.js.html",
    "src/remove.js",
    "file"
  ],
  [
    "src/swap.js",
    "file/src/swap.js.html",
    "src/swap.js",
    "file"
  ]
]